# define default database user, name, and password for PostgreSQL deployment
auth:
  enablePostgresUser: true
  postgresPassword: "Djdflheu13"
  username: "alex.molokov"
  password: "otus"
  database: "otus"

# The postgres helm chart deployment will be using PVC postgresql-data-claim
primary:
  persistence:
    enabled: true
    existingClaim: "postgresql-data-claim"

volumePermissions:
  enabled: true