{
 "title": "otus homework 5",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Active alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  { "title": "Alert status", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "API - create user - /api/v1/user [POST] ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(requests_total{url=\"/api/v1/user\",code=~\"5.*\",method=\"POST\"}[2m])) or\n      vector(0)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Время ответа",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user\", method=\"POST\"}[2m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user\", method=\"POST\"}[2m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user\", method=\"POST\"}[2m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user\", method=\"POST\"}[2m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Количество запросов в секунду",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "sum (rate(requests_total{url=\"/api/v1/user\", method=\"POST\"}[2m])) or vector(0)",
     "legendFormat": "create"
    }
   ]
  },
  {
   "title": "API - update user - /api/v1/user/{id} [PUT] ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(requests_total{url=\"/api/v1/user/{id}\",code=~\"5.*\",method=\"PUT\"}[2m])) or\n      vector(0)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Время ответа",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"PUT\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"PUT\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"PUT\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"PUT\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Количество запросов в секунду",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
   "targets": [
    {
     "expr": "sum (rate(requests_total{url=\"/api/v1/user/{id}\", method=\"PUT\"}[2m])) or vector(0)",
     "legendFormat": "update"
    }
   ]
  },
  {
   "title": "API - get user - /api/v1/user/{id} [GET] ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(requests_total{url=\"/api/v1/user/{id}\",code=~\"5.*\",method=\"GET\"}[2m])) or\n      vector(0)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Время ответа",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"GET\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"GET\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"GET\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"GET\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Количество запросов в секунду",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 27 },
   "targets": [
    {
     "expr": "sum (rate(requests_total{url=\"/api/v1/user/{id}\", method=\"GET\"}[2m])) or vector(0)",
     "legendFormat": "get"
    }
   ]
  },
  {
   "title": "API - delete user - /api/v1/user/{id} [DELETE] ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(requests_total{url=\"/api/v1/user/{id}\",code=~\"5.*\",method=\"DELETE\"}[2m])) or\n      vector(0)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Время ответа",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"DELETE\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"DELETE\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"DELETE\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(request_duration_seconds_bucket{url=\"/api/v1/user/{id}\", method=\"DELETE\"}[2m])) by (le)) or vector(0)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Количество запросов в секунду",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 36 },
   "targets": [
    {
     "expr": "sum (rate(requests_total{url=\"/api/v1/user/{id}\", method=\"DELETE\"}[2m])) or vector(0)",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "some errors special url",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(requests_total{url=\"/sometimes/error\",code=~\"5.*\",method=\"GET\"}[2m])) or\n      vector(0)",
       "legendFormat": "5xx"
      }
     ]
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(requests_total{url=~\"/api/v1/.*|/sometimes/error\",code=~\"5.*\"}[2m])) or\n      vector(0)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Время ответа",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 46 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{url=~\"/api/v1/.*|/sometimes/error\"}[2m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{url=~\"/api/v1/.*|/sometimes/error\"}[2m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{url=~\"/api/v1/.*|/sometimes/error\"}[2m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(request_duration_seconds_bucket{url=~\"/api/v1/.*|/sometimes/error\"}[2m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Количество запросов в секунду",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 46 },
   "targets": [
    {
     "expr": "sum (rate(requests_total{url=~\"/api/v1/.*|/sometimes/error\"}[2m])) or vector(0)",
     "legendFormat": "all"
    }
   ]
  }
 ]
}