---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.configmap" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
{{- if .Values.env }}
data:
{{toYaml .Values.env | indent 2 }}
{{- end }}
...