apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.ingress" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  {{- with .Values.ingress}}
  ingressClassName: {{ .className }}
  rules:
    - host: {{ .host }}
      http:
        paths:
          - pathType: {{ .pathType }}
            path: {{ .path }}
            backend:
              service:
                name: {{ include "app.service" $ }}
                port:
                  number: {{ .port }}
  {{- end }}