{{- if .Values.pvc}}
{{range .Values.pvc}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ $.Chart.Name }}-{{ $.Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
spec:
  storageClassName: {{ .storageClass }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}