---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.secret" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
  {{- if .Values.envSecret}}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
stringData:
{{ toYaml .Values.envSecret | indent 2}}
  {{- else }}
stringData: {}
  {{- end }}
...