---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.service" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
  ports:
    - port: {{ .Values.ingress.port }}
      targetPort: {{ .Values.port }}
      name: {{ .Values.portName }}
...